name: shared_design
description: Shared design system package
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: BigShouldersStencil
      fonts:
        - asset: assets/fonts/BigShouldersStencil-Regular.ttf
          weight: 400
        - asset: assets/fonts/BigShouldersStencil-Light.ttf
          weight: 300
        - asset: assets/fonts/BigShouldersStencil-Medium.ttf
          weight: 500
        - asset: assets/fonts/BigShouldersStencil-Bold.ttf
          weight: 700
        - asset: assets/fonts/BigShouldersStencil-ExtraBold.ttf
          weight: 800
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/